kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tekton
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ibmc-file-gold-gid
  volumeMode: Filesystem
