apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pr-kubeinvaders
spec:
  pipelineRef:
    name: build-kubeinvaders
  serviceAccountName: pipeline
  timeout: 0h10m0s
  workspaces:
    - name: git
      persistentVolumeClaim:
        claimName: tekton
