
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template-build-kubeinvaders
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pr-kubeinvaders-
      spec:
        pipelineRef:
          name: build-kubeinvaders
        serviceAccountName: pipeline
        timeout: 0h10m0s
        workspaces:
          - name: git
            persistentVolumeClaim:
              claimName: tekton
