apiVersion: v1
kind: Template
parameters:
  - name: DOMAIN
    required: true
metadata:
 name: kubeinvaders-argoapp-template
objects:
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: operators
      namespace: openshift-gitops
      annotations:
        argocd.argoproj.io/sync-wave: "100"
    spec:
      destination:
        namespace: openshift-operators
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: components/operators/base
        repoURL: 'https://github.com/thomas-mattsson/kubeinvaders-gitops'
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: servicemesh
      namespace: openshift-gitops
      annotations:
        argocd.argoproj.io/sync-wave: "150"
    spec:
      destination:
        namespace: istio-system
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: components/servicemesh/base
        repoURL: 'https://github.com/thomas-mattsson/kubeinvaders-gitops'
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: kubeinvaders
      namespace: openshift-gitops
      annotations:
        argocd.argoproj.io/sync-wave: "200"
    spec:
      destination:
        namespace: kubeinvaders
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        chart: kubeinvaders
        helm:
          parameters:
            - name: route_host
              value: kubeinvaders-kubeinvaders.${DOMAIN}
          valueFiles:
            - https://raw.githubusercontent.com/thomas-mattsson/kubeinvaders-gitops/main/components/kubeinvaders/helm/values.yaml
        repoURL: 'https://lucky-sideburn.github.io/helm-charts'
        targetRevision: 1.9.2
      syncPolicy:
        automated:
          selfHeal: true
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: operators
      namespace: openshift-gitops
      annotations:
        argocd.argoproj.io/sync-wave: "180"
    spec:
      destination:
        namespace: openshift-operators
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: components/servicemesh/bookinfo/base
        repoURL: 'https://github.com/thomas-mattsson/kubeinvaders-gitops'
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: kubeinvaders-gitops
      namespace: openshift-gitops
      annotations:
        argocd.argoproj.io/sync-wave: "200"
    spec:
      destination:
        namespace: kubeinvaders
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: components/kubeinvaders/base
        repoURL: 'https://github.com/thomas-mattsson/kubeinvaders-gitops'
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
