apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeinvaders
  namespace: openshift-gitops
spec:
  destination:
    namespace: kubeinvaders
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: kubeinvaders
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/thomas-mattsson/kubeinvaders-gitops/main/components/kubeinvaders/helm/values.yaml
    repoURL: 'https://lucky-sideburn.github.io/helm-charts'
    targetRevision: 1.9.2
  syncPolicy:
    automated:
      selfHeal: true
