apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeinvaders
  namespace: openshift-gitops
spec:
  destination:
    namespace: kubeinvaders
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: kubeinvaders
    helm:
      parameters:
        - name: route_host
          value: >-
            kubeinvaders-kubeinvaders.mydomain.example.com
        - name: deployment.image.tag
          value: latest
        - name: deployment.image.repository
          value: >-
            image-registry.openshift-image-registry.svc:5000/kubeinvaders/kubeinvaders
        - name: config.target_namespace
          value: kubeinvaders
    repoURL: 'https://lucky-sideburn.github.io/helm-charts'
    targetRevision: 1.9.2
  syncPolicy:
    automated:
      selfHeal: true
