apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  version: v2.3
  tracing:
    type: Jaeger
    sampling: 10000
  addons:
    jaeger:
      name: jaeger
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
      name: kiali
    grafana:
      enabled: true
  # Disabling automatic route creation from gateways since ArgoCD can't be configured to ignore them
  istio:
    gateways:
      istio-ingressgateway:
        ior_enabled: false
  
