kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: extra-argo-role
rules:
  - verbs:
      - '*'
    apiGroups:
      - tekton.dev
      - route.openshift.io
      - triggers.tekton.dev
      - monitoring.coreos.com
    resources:
      - '*'
  - verbs:
      - create
      - delete
    apiGroups:
      - ""
    resources:
      - serviceaccounts
      - services
